### ISSUE TITLE
Cannot execute runApp again until restarting R session

### ISSUE THREAD

**Issue by bearloga** [Ironholds/rainbow#12]
```{r}
> shiny::runApp()
Loading required package: shiny

Listening on http://127.0.0.1:4469

Attaching package: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box

Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Using events as value column: use value.var to override.
Using events as value column: use value.var to override.
Using events as value column: use value.var to override.
Using events as value column: use value.var to override.
```

*[stops app]*
*[runs it again]*

```{r}
> shiny::runApp()

Listening on http://127.0.0.1:4469
Using events as value column: use value.var to override.
Using events as value column: use value.var to override.
Using events as value column: use value.var to override.
Using events as value column: use value.var to override.
Error in xts(data[, -1], data[, 1]) : 
  order.by requires an appropriate time-based object
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer

> 
```

Not sure if this is just on my machine. @Ironholds, care to confirm?

**Comment by Ironholds** [comment]
Works fine for me. How are you stopping it?

**Comment by bearloga** [comment]
Stopping in RStudio with button. Also same `xts(data[, -1], data[, 1])` error when restarting app, but this only the case with 6230f396ea4ffc33d1e347c58b4dabc2267b5f53 and not acab675698f3fbb80d6915dba51727d7bbd62435 even though I didn't change anything related to that stuff.

**Comment by Ironholds** [comment]
Huuuuuhh. No idea!

**Comment by bearloga** [comment]
Oops.

**Comment by bearloga** [comment]
Narrowed it down to

```{r}
xts(desktop_load_data[,-1], desktop_load_data[,1])
# Error in xts(desktop_load_data[, -1], desktop_load_data[, 1]) : 
#   order.by requires an appropriate time-based object
```

Okay…

```{r}
> desktop_load_data[,1]
Source: local data frame [107 x 1]

    timestamp
1  2015-04-14
2  2015-04-15
3  2015-04-16
..        ...
```

And **this** is where it gets really weird.

```{r}
> class(desktop_load_data[,1])
[1] "tbl_df"     "data.frame"

> class(desktop_load_data$timestamp)
[1] "Date"
```

I may have an idea of how to fix this.

**Comment by Ironholds** [comment]
There shouldn't be a bug there to start with. What packages do you have loaded?

**Comment by bearloga** [comment]
ggplot2, RColorBrewer, reshape2, xts, zoo, readr, markdown, dygraphs, shinydashboard, shiny

(and stats, graphics, grDevices, utils, datasets, methods, base)

**Comment by Ironholds** [comment]
huuuuh. Wait; is this existing or new code?

**Comment by bearloga** [comment]
New code (6230f396ea4ffc33d1e347c58b4dabc2267b5f53)

**Comment by Ironholds** [comment]
Dplyr as a dependency? Oy.

Check out utils.R, specifically the defaults on make_dygraph - there's some custom logic there for handling tidy data with only one unique variable so that the names don't go silly. That's probably the cause.

**Comment by bearloga** [comment]
I'm with you on that oy. dplyr masks so much stuff that I avoided `library(dplyr)`

The problem is that for some weird reason `data[, 1]` isn't a `Date` object that `xts()` can use to `order.by` even though `data[[1]]` is.

```{r}
> class(desktop_load_data[,1])
[1] "tbl_df"     "data.frame"

> class(desktop_load_data[[1]])
[1] "Date"
```

BUT only when the app was re-run. When it was a fresh run, everything goes smoothly. *[shrug]*

**Comment by Ironholds** [comment]
Well, you'll need to load dplyr if you want it to be reproducible code; you're assuming dplyr on the system the code is run by.

**Comment by bearloga** [comment]
Yes, because I included it as a dependency in README. So it's installed but not loaded.

**Comment by bearloga** [comment]
Getting rid of dplyr in next commit :)
